# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
FlatRate.create({route: 'O\'hare - Downtown', duration: 1})
FlatRate.create({route: 'O\'hare - South Loop', duration: 1.25})
FlatRate.create({route: 'O\'hare - Chicago North', duration: 1})
FlatRate.create({route: 'O\'hare - Chicago West', duration: 0.75})
FlatRate.create({route: 'O\'hare - Evanston', duration: 1})
FlatRate.create({route: 'O\'hare - Skokie', duration: 0.75})
FlatRate.create({route: 'O\'hare - Chicago NW', duration: 0.75})
FlatRate.create({route: 'O\'hare - Wilmette', duration: 1})
FlatRate.create({route: 'O\'hare - Winetka', duration: 1})
FlatRate.create({route: 'O\'hare - Northbrook', duration: 1})
FlatRate.create({route: 'O\'hare - Deerfield', duration: 1.25})
FlatRate.create({route: 'O\'hare - Barrington', duration: 1.25})
FlatRate.create({route: 'O\'hare - Naperville', duration: 1.25})
FlatRate.create({route: 'O\'hare - Oak Park', duration: 1.25})
User.create({name: 'guest', username: 'guest', password: 'pass', phone_number: '773-294-8839'})
Driver.create({name: 'John Smith', username: 'John', phone_number: '773-320-3232', photo: 'https://bookadriver.s3.us-east-2.amazonaws.com/driver.jpeg', description: 'Ultra luxury', rate:100, car: 'Mercedes-Maybach ', car_photo: 'https://bookadriver.s3.us-east-2.amazonaws.com/car.png', rating:4.53, off_duty: '0'})
Driver.create({name: 'Craig Accardi', username: 'Craig', phone_number: '312-323-3842', photo: 'https://bookadriver.s3.us-east-2.amazonaws.com/driver1.jpeg', description: 'Ultra luxurious vehicle', rate:140, car: 'Bentley Continental', car_photo: 'https://bookadriver.s3.us-east-2.amazonaws.com/car3.jpg', rating:4.23, off_duty: '0'})
Driver.create({name: 'Greg Wilson', username: 'Greg', phone_number: '773-890-5243', photo: 'https://bookadriver.s3.us-east-2.amazonaws.com/driver2.jpeg', description: 'Best service in town!', rate:100, car: 'Mercedes Benz 550', car_photo: 'https://bookadriver.s3.us-east-2.amazonaws.com/car2.jpg', rating:4.11, off_duty: '0'})
Driver.create({name: 'Matt Brown', username: 'Matt', phone_number: '773-320-3232', photo: 'https://bookadriver.s3.us-east-2.amazonaws.com/driver3.jpeg', description: 'Reliability is my goal!', rate:175, car: 'Lincoln Continental', car_photo: 'https://bookadriver.s3.us-east-2.amazonaws.com/limo.jpg', rating:4.65, off_duty: '0'})
Driver.create({name: 'Julia Jones', username: 'Julia', phone_number: '312-888-1234', photo: 'https://bookadriver.s3.us-east-2.amazonaws.com/image.jpeg', description: 'Respectful driver, always on time', rate:85, car: 'Lincoln Continental', car_photo: 'https://bookadriver.s3.us-east-2.amazonaws.com/car1.jpg', rating:4.56, off_duty: '0'})
Driver.create({name: 'Erica', username: 'Erica', phone_number: '773-322-3232', photo: 'https://bookadriver.s3.us-east-2.amazonaws.com/Erica.png', description: 'I love driving!', rate:100, car: 'Audi Q5', car_photo: 'https://bookadriver.s3.us-east-2.amazonaws.com/Audi-Erica.jpg', rating:4.88, off_duty: '0'})
Driver.create({name: 'Bruce', username: 'Bruce', phone_number: '312-888-4234', photo: 'https://bookadriver.s3.us-east-2.amazonaws.com/Bruce.png', description: 'First come, first served!', rate:155, car: 'Jaguar', car_photo: 'https://bookadriver.s3.us-east-2.amazonaws.com/Jag-Bruce.jpg', rating:4.78, off_duty: '0'})
Driver.create({name: 'David Martinez', username: 'David', phone_number: '312-883-4732', photo: 'https://bookadriver.s3.us-east-2.amazonaws.com/dr10.jpeg', description: 'Top service', rate:125, car: 'Chrysler', car_photo: 'https://bookadriver.s3.us-east-2.amazonaws.com/chrysler.jpg', rating:4.78, off_duty: '0'})
Driver.create({name: 'Adrian P', username: 'Adrian', phone_number: '312-883-4732', photo: 'https://bookadriver.s3.us-east-2.amazonaws.com/dr13.jpeg', description: 'Top service', rate:105, car: 'Chevrolet Suburban', car_photo: 'https://bookadriver.s3.us-east-2.amazonaws.com/suburban.jpg', rating:4.35, off_duty: '0'})
Driver.create({name: 'Carla G', username: 'Carla', phone_number: '312-883-4732', photo: 'https://bookadriver.s3.us-east-2.amazonaws.com/dr12.jpeg', description: 'Best service!', rate:90, car: 'GMC Yukon', car_photo: 'https://bookadriver.s3.us-east-2.amazonaws.com/yukon.jpg', rating:4.21, off_duty: '0'})
Driver.create({name: 'Yang Li', username: 'Yang', phone_number: '312-883-4732', photo: 'https://bookadriver.s3.us-east-2.amazonaws.com/dr11.jpeg', description: 'High quality vehicle', rate:125, car: 'Cadillac Escalade', car_photo: 'https://bookadriver.s3.us-east-2.amazonaws.com/escalade.jpg', rating:4.70, off_duty: '0'})
